const fs = require('fs');
const package = require( __dirname + '/../package.json' );

const body = [
    `
/**
 * This file is generated by scripts/imports.js
 * Do NOT edit this file directly. Edit scripts/imports.js instead.
 * 
 * This file is used to import all dependencies of the project.
 * This is necessary because Webpack does not support dynamic imports.
 */
`.trim()
]

const deps = Object.keys( package.dependencies ).map( dep => `import '${dep}';` );

body.push( ...deps );

fs.writeFileSync( __dirname + '/../src/imports.ts', body.join('\n') );