/**
 * This file is generated by scripts/imports.js
 * Do NOT edit this file directly. Edit scripts/imports.js instead.
 * 
 * This file is used to import all dependencies of the project.
 * This is necessary because Webpack does not support dynamic imports.
 */
import 'buffer';
import 'process';