name: Create Draft Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Zip the package
        run: zip -r dist/module.zip ./  # Replace 'dist/' with the directory you want to zip

      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name || 'manual-release' }}
          release_name: ${{ github.ref_name || 'Manual Release' }}
          draft: true
          prerelease: false
          body_path: ./README.md

      - name: Upload webpack to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './dist/dbpf.web.js'
          asset_name: 'dbpf.web.js'
          asset_content_type: application/octet-stream

      - name: Upload zip to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './dist/module.zip'
          asset_name: 'module.zip'
          asset_content_type: application/octet-stream
